added checks that functions with explicitly given codomains actually …
AlgebraicJulia/Catlab.jl pull request #759
Opened 2023-04-05 00:28 UTC by KevinArlin

…have range in the codomain.

required adding in to typesets.

Also a little fiddling with which function constructors allow how many args; generally you should now never make it past FinFunction or FinDomFunction into the helper constructors without a codomain.

Fixes #751 .

2023-04-05 04:03 UTC, epatters commented
Thanks Kevin, and congrats on your first PR!

Looks like there are some test failures, so that's the first thing to resolve.

2023-04-05 22:08 UTC, KevinArlin commented
Whoops, let's try this!

2023-04-06 18:01 UTC, epatters requested changes

2023-04-06 18:01 UTC, epatters commented on test/runtests.jl
> +
Looks like a spurious newline crept in here.

2023-04-06 18:47 UTC, KevinArlin commented on src/categorical_algebra/FinSets.jl
> +end
Currently, no constructor allows the user to explicitly provide the domain of a `FinDomFunction` given as  avector and which is going to be indexed. Of course this is never necessary but I tried to do it once organically and it seems nice to support it for every variant.

2023-04-11 17:49 UTC, KevinArlin commented on src/categorical_algebra/FinSets.jl
> +end
Alright, I think I've got what I wanted here now.

2023-04-11 21:46 UTC, epatters approved these changes
Thanks Kevin, LGTM!

2023-04-11 21:46 UTC, merged