Iss598
AlgebraicJulia/Catlab.jl pull request #762
Opened 2023-04-11 21:18 UTC by KevinArlin

Fixes #598 by having `@finfunctor` tell the user which morphisms are mapped inconsistently with the object map. There is code ready to update `@finfunctor` to check preservation of equations between morphisms in the domain category, too, once we have some ability to check equality of homs.

2023-04-18 20:17 UTC, olynch commented
@mehalter @KevinArlin, what's our feeling about the failing tests on nightly? Is this a bug in nightly? Should we disable nightly CI until it's fixed? I don't want to merge this with failing tests.

2023-04-21 17:52 UTC, olynch approved these changes
Overall looks good; I saw one minor thing that you might want to change but it doesn't really matter it's just something good to know.

2023-04-21 17:52 UTC, olynch commented on src/programs/DiagrammaticPrograms.jl
> +    Expr(_...) => error("""
This can just be `_`, not `Expr(_...)`

2023-05-03 21:01 UTC, epatters requested changes
Thanks Kevin! In addition to Owen's comment, I have a few small comments too.

Beyond that, the main thing that's bothering me is that naturality and functorality testing now have completely different APIs: the former uses a keyword argument `return_failures` and the latter has separate function `get_nonfunctoralities`.

It doesn't have to be in this PR, but before doing a release I'd like to make this consistent. My suggestion would be to have no keyword arguments and use:

- `is_natural` and `naturality_failures`
- `is_functorial` and `functorality_failures`

I'm open to other conventions if you have ideas. I would suggest not prefixing with `get_` since this is generally (though not always) avoided in Julia APIs.

2023-05-03 21:08 UTC, epatters commented
Oh, @KevinArlin, I see that #765 you also add a `get_unnaturalities` function. I think I'd prefer a different naming convention but, more importantly, this does address my complaint about having inconsistent APIs for naturality and functorality testing.

2023-05-12 04:55 UTC, epatters approved these changes

2023-05-12 04:55 UTC, merged