VM-based homomorphism search
AlgebraicJulia/Catlab.jl pull request #830
Opened 2023-07-15 20:06 UTC by olynch

2024-01-08 22:20 UTC, kris-brown commented
Future work:

- Handle attributes
- Sample random codomains and optimize the compiled program  
- Convert program into an actual julia function rather than interpreting the VM
- Load instruction has `f` as a symbol, so dynamic dispatch used. This could be made static.

2024-04-08 22:06 UTC, epatters requested changes

2024-04-08 22:06 UTC, epatters commented on test/categorical_algebra/HomSearch.jl
> +using Catlab.CategoricalAlgebra.HomSearch: compile_search
If we need to do this in both the benchmarks and the tests, perhaps we should be exporting a function named `compile_hom_search` or something similar. (I think `compile_search` is a little vague.)

2024-04-08 22:20 UTC, epatters approved these changes

2024-04-09 00:33 UTC, merged