Separate CSet search problems (e.g. HomSearch) into separate file
AlgebraicJulia/Catlab.jl pull request #843
Opened 2023-08-30 20:54 UTC by kris-brown

This PR simply migrates some code from `CSets.jl` to a new file `HomSearch.jl`. 

(Also a minor cleanup of replacing `out_homs(S,c)` and `in_homs(S,c)` with `homs(S; to=c)` and `homs(S; from=c)`.)

2023-09-01 00:11 UTC, epatters requested changes
Thanks Kris! This looks good apart from one small comment.

2023-09-01 00:11 UTC, epatters commented on src/categorical_algebra/HomSearch.jl
> +"""
This docstring can become the module-level docstring, i.e., be moved to the very top of the file.

2023-09-02 02:14 UTC, epatters requested changes
Sorry, I didn't notice this the first time, but shouldn't we also reorganize the tests accordingly?

2023-09-02 20:07 UTC, kris-brown commented
Good point! There are still some calls to `homomorphism` in `CSets.jl` but the dedicated hom search and subobject search is now moved

2023-09-03 02:14 UTC, epatters approved these changes
Thanks Kris!

2023-09-03 02:14 UTC, merged