Smoothing interaction between attrstuff and actual sets and functions
AlgebraicJulia/Catlab.jl pull request #900
Opened 2024-04-19 19:31 UTC by KevinDCarlson

The changes below are to enable smoother data migrations of acsets with some `AttrVar` attribute values as requested here: https://github.com/AlgebraicJulia/DataMigrations.jl/issues/159

2024-04-22 21:31 UTC, kris-brown approved these changes
These seem like reasonable casting functions! LGTM

2024-04-22 21:39 UTC, KevinDCarlson commented
@epatters Could you merge this and do a patch release?

2024-04-23 01:51 UTC, epatters requested changes
Though the additions are simple, if they are to be part of the public API of Catlab, then they should have tests, which is what will ensure that they remain stable over time. I think the important thing to add tests for is the conversion between SetOb/FinSets and VarSets.

2024-05-07 18:02 UTC, epatters approved these changes
Thanks Kevin! I'll merge once the CI finishes.

2024-05-07 18:14 UTC, merged